### ISSUE TITLE
Fix SAML for JRuby 1.7.20+

### ISSUE THREAD

**Issue by ryanfb** [sosol/sosol#64] opened 2015-06-18 21:35 UTC
Tests pass under JRuby 1.7.19, but changing to 1.7.20 or 1.7.20.1 results in a slew of `Java::JavaLang::NullPointerException`s in `RubySamlTest`.

**Comment by balmas** [comment] 2015-07-08 02:09
I'm not sure if this was testing the included version of the ruby-saml lib, or the newer 1.0.0 gem. The latter is what we need to move to in order to get full xml encryption and signing support (per #53), but the ruby-saml 1.0.0 tests are failing under jruby 1.9+ too :)

Some WIP notes after a day spent debugging this:

1) a saxon upgrade is required in order to get the fix for https://saxonica.plan.io/issues/1944 . Saxon 9.6 resolves this problem (which manifests in a configuration error when Nokogiri retrieves the canonicalization elements in xml_security.rb)

2) there appears to be a bug in Jruby OpenSSL https://github.com/jruby/jruby/issues/1819 . I have confirmed with a build of jruby-openssl with this fix https://github.com/balmas/jruby-openssl/commit/f3a0964ecad5b788c82431b3a4863957d9f1b233 that it does fix the "data hash wrong" error when decrypting docs encoded with OAEPWithSHA1AndMGF1Padding. Before I can submit a pull request I need to add a test. It doesn't break anything but should add a test to demonstrate the purpose of the fix.

3) We still need to merge a fix into the ruby-saml code to support scoped eduPersonTargetedId. I have this in my fork right now in commit https://github.com/balmas/ruby-saml/commit/2e1794581966d46ef7f2e0f15679d85880812542 . Before I can submit a pull request to the ruby-saml developers I need to clean this up and add a test or two.

With the above changes, running on both jruby 1.7.16 and 1.7.19 with JDK 1.8 and the additional shib controller code changes in the ruby-saml-upgrade branch the basic auth sequence succeeds with the Tufts IdP.  Some tests on the ruby-saml gem still fail unfortunately but they don't seem to be features I'm using.

Before we can close this I need to 
- [ ] finish and submit the pull request on  jruby-openssl
- [ ] finish and submit the pull request on ruby-saml
- [ ] fix the Gemfile to use these libs from my github repo for now (or put into the sosol repo...)
- [ ] make sure the changes didn't break anything else
- [ ] decide if we can live with the rest of the ruby-saml tests failing
- [ ] clean up the handling of the scoped eduPersonTargetedId in the shib_controller to make this come from the config and fallback to

**Comment by ryanfb** [comment] 2015-07-08 12:42
For 1), I recently bumped to Saxon 9.5.1.10 for #62 under the assumption that 9.5.* was "stable" (and would presumably require fewer API changes, though it did require some). But I have no real objection to just going with latest as long as everything else we do with it still works.

**Comment by balmas** [comment] 2015-07-08 22:52
Pull requests submitted to jruby-openssl https://github.com/jruby/jruby-openssl/pull/54
and ruby-saml https://github.com/onelogin/ruby-saml/pull/251

**Comment by balmas** [comment] 2015-07-11 20:38
Yay! ruby-saml fix accepted and merged.

**Comment by balmas** [comment] 2015-07-13 11:48
jruby-openssl fix also accepted and merged (master branch)

**Comment by balmas** [comment] 2015-07-15 12:51
@ryanfb the saxonhe 9.6 jar is now in the rails-3-perseus-merge branch -- it required the fix in 21575f2 to get tests to pass. I will test in the UI a bit too to make sure I don't uncover any additional errors.

I have now removed all of the local embedded ruby-saml code from this branch as well, including the test, since we will be using the unmodified ruby-saml gem when we deploy.

**Comment by ryanfb** [comment] 2015-07-15 17:54
Looks good to me!

**Closed** 2015-07-15 18:10 UTC
Labels: testing

**Comment by balmas** [comment] 2015-07-15 18:37
Remaining open checklist items in above comments handled separately in #53 and #74
