### ISSUE TITLE
U+0027 appears to break Leiden+

### ISSUE THREAD

**Issue by jcowey** [sosol/sosol#111] opened 2015-09-10 13:59 UTC
Leiden+ spins and spins if there is an instance of

U+0027

in the text.

If one replaces this with 
U+2019
Leiden+ saves

This did not used to happen. 

While I know that U+2019 is preferred, I think that entering U+0027 should not break Leiden+, because many contributors use U+0027 regularly.

**Comment by hcayless** [comment] 2015-09-10 14:45
The problem isn’t in XSugar. http://libdc3-dev-03.oit.duke.edu/xsugar deals with it just fine. Maybe there’s a string-escaping issue downstream from XSugar. Likely in the Javascript that loads the Leiden+ view...

**Comment by ryanfb** [comment] 2015-09-10 15:08
Should be fixed by 3c10e5e08d51ebafb24b58c20f081efb61a20d34.

**Closed by ryanfb** 2015-09-10 15:08 UTC

**Comment by jcowey** [comment] 2015-09-10 15:29
Seem to work well now. Thanks
